baseURL: "https://www.asyncdjango.com/"
theme: "up-business-theme"
languageCode: "en-us"

title: "Async Patterns in Django"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "Async Patterns in Django"
  description: "recipes for asynchronous code and protocols in Django"
  images: 
    - "images/hero-image.png"

  logo: "arrow-up.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    twitter: "https://twitter.com/pizzapanther"

  # location:
  #   - "3891 Ranchview Dr. Richardson, California 62639"
  #   - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "paul@neutron.studio"

  copyright: "© 2024 Paul Bailey"

menus:
  main:
    - name: "Buy on LeanPub"
      url: "/#hero"
      weight: 1

    - name: "Buy on Amazon"
      url: "/#"
      weight: 2

  buttons:
    - name: "Book a call"
      url: "/#"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "LeanPub (epub)"
      url: "/#hero"
      weight: 1

    - name: "Amazon (Kindle and Paperback)"
      url: "/#"
      weight: 2

taxonomies:
  series: "series"
  tags: "tags"
